# Generated by Django 5.0.1 on 2024-03-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FileField(default=1, unique=True, upload_to='static/images'),
            preserve_default=False,
        ),
    ]
