# Generated by Django 5.0.1 on 2024-03-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_alter_blog_image_alter_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='static/images'),
        ),
    ]
